Changement dans GraphMPM
TeddyBoomer/grapheMPM pull request #4
Opened 2020-04-02 10:04 UTC by Achollet77

Pour obtenir un graph MPM dont les arcs partent des sommets et non des dates

2020-04-02 11:46 UTC, Achollet77 commented
@TeddyBoomer was it possible to change your code in order to make edge start from node name and not from dates ?

2020-04-17 11:38 UTC, TeddyBoomer commented
> @TeddyBoomer was it possible to change your code in order to make edge start from node name and not from dates ?

Bonjour, je vais enfin avoir le temps de me pencher sur la question; une autre modification (affichage des niveaux) avait aussi été demandée; il faut que je vois tout de même sur quelle ligne se branchent les arcs suivant la présentation des dates en dessous.
cordialement,

2020-04-25 08:46 UTC, TeddyBoomer requested changes
Bonjour, pouvez-vous laissez les anciennes lignes de code en commentaire:
ça permet de garder une réactivation possible, car c'est un choix esthétique après tout.

2020-04-25 13:57 UTC, TeddyBoomer commented
rebonjour, après test sur une branche expérimentale, ça convient; comme il va y avoir beaucoup de nouveautés, je n'intègre pas ce pull request mais je l'ai bien pris en compte dans la version à venir.

2020-04-25 13:57 UTC, closed without merging